/* eslint-disable @next/next/no-img-element */
/**
 * Shared layout for every Open Graph / Twitter card generated by the site.
 * Sized to the standard 1200x630 social-card aspect.
 *
 * The actual `ImageResponse` is constructed by each route's
 * `opengraph-image.tsx`. This module only exports the JSX template and a
 * font-fetching helper.
 */

export const SITE_NAME = "AI PM Playbook";
export const SITE_URL_LABEL = "ai-pm-playbook.com";

export type OgCategory =
  | "Playbook"
  | "Guide"
  | "Template"
  | "Case study"
  | "Home";

export type OgAccent = "peach" | "lavender" | "mint" | "butter" | "rose" | "sky";

const accentBg: Record<OgAccent, string> = {
  peach:
    "radial-gradient(closest-side, rgba(244,162,102,0.55), rgba(255,222,196,0.20) 60%, transparent 80%)",
  lavender:
    "radial-gradient(closest-side, rgba(189,165,222,0.55), rgba(225,215,240,0.20) 60%, transparent 80%)",
  mint:
    "radial-gradient(closest-side, rgba(160,198,175,0.55), rgba(213,232,220,0.20) 60%, transparent 80%)",
  butter:
    "radial-gradient(closest-side, rgba(255,220,90,0.55), rgba(255,232,140,0.20) 60%, transparent 80%)",
  rose:
    "radial-gradient(closest-side, rgba(232,132,132,0.55), rgba(245,188,188,0.20) 60%, transparent 80%)",
  sky:
    "radial-gradient(closest-side, rgba(118,168,220,0.55), rgba(170,200,232,0.20) 60%, transparent 80%)",
};

const categoryAccent: Record<OgCategory, OgAccent> = {
  Home: "peach",
  Playbook: "peach",
  Guide: "lavender",
  Template: "mint",
  "Case study": "butter",
};

/**
 * Fetch a Google Font binary at build time. Returns ArrayBuffer suitable for
 * passing to ImageResponse's `fonts` option.
 */
export async function loadGoogleFont(
  family: string,
  weight: number = 400,
  italic = false,
): Promise<ArrayBuffer> {
  const cssUrl = `https://fonts.googleapis.com/css2?family=${encodeURIComponent(
    family,
  )}:${italic ? "ital," : ""}wght@${italic ? "1," : ""}${weight}&display=swap`;
  const css = await fetch(cssUrl, {
    headers: {
      // Force the woff2 / ttf url to surface in the CSS
      "User-Agent":
        "Mozilla/5.0 (Macintosh; Intel Mac OS X 13_5) AppleWebKit/537.36",
    },
  }).then((r) => r.text());
  const m = css.match(/src: url\((https?:\/\/[^)]+)\)/);
  if (!m) {
    throw new Error(`Could not parse font URL from Google Fonts CSS for ${family}`);
  }
  return fetch(m[1]).then((r) => r.arrayBuffer());
}

type OgFrameProps = {
  title: string;
  eyebrow?: string;
  category?: OgCategory;
};

export function OgFrame({ title, eyebrow, category = "Home" }: OgFrameProps) {
  const accent = categoryAccent[category];
  // Slightly smaller font for very long titles
  const len = title.length;
  const titleFontSize = len > 60 ? 60 : len > 38 ? 72 : 88;

  return (
    <div
      style={{
        width: "100%",
        height: "100%",
        display: "flex",
        flexDirection: "column",
        justifyContent: "space-between",
        padding: "64px 72px",
        background: "#f5f3ef",
        color: "#0a0a0a",
        fontFamily: '"Geist", "Inter", system-ui, sans-serif',
        position: "relative",
      }}
    >
      {/* Decorative orb */}
      <div
        style={{
          position: "absolute",
          top: -160,
          right: -120,
          width: 540,
          height: 540,
          borderRadius: 9999,
          background: accentBg[accent],
        }}
      />
      <div
        style={{
          position: "absolute",
          bottom: -200,
          left: -160,
          width: 480,
          height: 480,
          borderRadius: 9999,
          background: accentBg.lavender,
          opacity: 0.6,
        }}
      />

      {/* Top row */}
      <div
        style={{
          display: "flex",
          alignItems: "center",
          justifyContent: "space-between",
          zIndex: 1,
        }}
      >
        <div style={{ display: "flex", alignItems: "center", gap: 16 }}>
          <div
            style={{
              width: 52,
              height: 52,
              borderRadius: 14,
              background: "#0a0a0a",
              color: "#f5f3ef",
              display: "flex",
              alignItems: "center",
              justifyContent: "center",
              fontWeight: 600,
              fontSize: 18,
              letterSpacing: -0.4,
            }}
          >
            PM
          </div>
          <div style={{ display: "flex", fontSize: 26, fontWeight: 500, letterSpacing: -0.5 }}>
            {SITE_NAME}
          </div>
        </div>
        {category !== "Home" ? (
          <div
            style={{
              display: "flex",
              fontSize: 18,
              fontWeight: 500,
              letterSpacing: 4,
              textTransform: "uppercase",
              color: "rgba(10,10,10,0.55)",
            }}
          >
            {category}
          </div>
        ) : null}
      </div>

      {/* Center: title block */}
      <div
        style={{
          display: "flex",
          flexDirection: "column",
          gap: 22,
          zIndex: 1,
        }}
      >
        {eyebrow ? (
          <div
            style={{
              display: "flex",
              fontSize: 22,
              fontWeight: 500,
              letterSpacing: 4,
              textTransform: "uppercase",
              color: "rgba(10,10,10,0.55)",
            }}
          >
            {eyebrow}
          </div>
        ) : null}
        <div
          style={{
            display: "flex",
            fontSize: titleFontSize,
            fontWeight: 500,
            letterSpacing: -2,
            lineHeight: 1.02,
            color: "#0a0a0a",
            maxWidth: 960,
          }}
        >
          {title}
        </div>
      </div>

      {/* Bottom row */}
      <div
        style={{
          display: "flex",
          alignItems: "center",
          justifyContent: "space-between",
          zIndex: 1,
        }}
      >
        <div style={{ display: "flex", fontSize: 24, color: "rgba(10,10,10,0.55)" }}>
          {SITE_URL_LABEL}
        </div>
        <div
          style={{
            display: "flex",
            alignItems: "center",
            gap: 10,
            fontSize: 18,
            color: "rgba(10,10,10,0.55)",
          }}
        >
          <div
            style={{
              width: 26,
              height: 26,
              borderRadius: 9999,
              background: accentBg[accent],
              border: "1px solid rgba(10,10,10,0.08)",
            }}
          />
          A working system for AI PMs
        </div>
      </div>
    </div>
  );
}

export const OG_SIZE = { width: 1200, height: 630 } as const;
export const OG_CONTENT_TYPE = "image/png" as const;
